	
SRCFOLDER= src/
TESTFOLDER= test/
SOURCES= $(SRCFOLDER)child.o \
		 $(SRCFOLDER)signal.o \
		 $(SRCFOLDER)debug.o \
		 $(SRCFOLDER)avl.o \
		 $(SRCFOLDER)logging.o 

MAIN= $(SRCFOLDER)main.o
TEST= $(TESTFOLDER)test.o

CFLAGS= -D_POSIX_SOURCE=200112L \
		-std=c99 \
		-Wall \
		-Iinclude 
	#	-U_GNU_SOURCE \

LDFLAGS= -lpthread

# Name of our executable
EXE = server

all: $(SOURCES) link

#%.o: %.c
#	$(CC) $(CFLAGS) $(CPPFLAGS) $(INCLUDES) $(TARGET_ARCH)\
#		-c $(INPUT) -o $(OUTPUT)

src/main.o: $(SRCFOLDER)main.c
	gcc $(CFLAGS) -c $(SRCFOLDER)main.c

link:
	gcc $(LDFLAGS) -o $(EXE) $(SOURCES) $(MAIN)

clean:
	@echo "Removing $(EXE)..."
	-rm $(EXE) &>/dev/null
	@echo "Removing all *.o files...\n"
	-rm -R src/*.o &>/dev/null

test:
	gcc $(LDFLAGS) -o $(TESTEXE) $(SOURCES) $(TEST)


